name: root_detection
description: "A root detection Flutter plugin project."
version: 1.0.1
repository: https://github.com/sonic009/root_detection
homepage: https://github.com/sonic009/root_detection

license: MIT


environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.root_detection
        pluginClass: RootDetectionPlugin
      ios:
        pluginClass: RootDetectionPlugin
        suggestedMinimumOSVersion: "15.8"
